/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CertificateItem: typeof import('./src/components/certificate-item/src/CertificateItem.vue')['default']
    Choice: typeof import('./src/components/subject/choice/Choice.vue')['default']
    CourseItem: typeof import('./src/components/course-item/src/CourseItem.vue')['default']
    ExamItem: typeof import('./src/components/exam-item/src/ExamItem.vue')['default']
    Judgement: typeof import('./src/components/subject/judgement/Judgement.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutCellGroup: typeof import('@nutui/nutui-taro')['CellGroup']
    NutCheckbox: typeof import('@nutui/nutui-taro')['Checkbox']
    NutCol: typeof import('@nutui/nutui-taro')['Col']
    NutCountdown: typeof import('@nutui/nutui-taro')['Countdown']
    NutDialog: typeof import('@nutui/nutui-taro')['Dialog']
    NutDivider: typeof import('@nutui/nutui-taro')['Divider']
    NutEmpty: typeof import('@nutui/nutui-taro')['Empty']
    NutForm: typeof import('@nutui/nutui-taro')['Form']
    NutFormItem: typeof import('@nutui/nutui-taro')['FormItem']
    NutGrid: typeof import('@nutui/nutui-taro')['Grid']
    NutGridItem: typeof import('@nutui/nutui-taro')['GridItem']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutMenu: typeof import('@nutui/nutui-taro')['Menu']
    NutMenuItem: typeof import('@nutui/nutui-taro')['MenuItem']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutProgress: typeof import('@nutui/nutui-taro')['Progress']
    NutRadio: typeof import('@nutui/nutui-taro')['Radio']
    NutRadioGroup: typeof import('@nutui/nutui-taro')['RadioGroup']
    NutRow: typeof import('@nutui/nutui-taro')['Row']
    NutSearchbar: typeof import('@nutui/nutui-taro')['Searchbar']
    NutSpace: typeof import('@nutui/nutui-taro')['Space']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
    NutTabPane: typeof import('@nutui/nutui-taro')['TabPane']
    NutTabs: typeof import('@nutui/nutui-taro')['Tabs']
    NutTag: typeof import('@nutui/nutui-taro')['Tag']
    NutTextarea: typeof import('@nutui/nutui-taro')['Textarea']
    NutUploader: typeof import('@nutui/nutui-taro')['Uploader']
    Parser: typeof import('./src/components/parser/src/Parser.vue')['default']
    ProfessionItem: typeof import('./src/components/profession-item/src/ProfessionItem.vue')['default']
    ShortAnswer: typeof import('./src/components/subject/shortAnswer/ShortAnswer.vue')['default']
    WebView: typeof import('./src/components/webview/src/WebView.vue')['default']
  }
}
